### PR TITLE
[firmware-upgrader] Add badges #4

### LINKED ISSUE #4: [firmware-upgrader] Add badges
Add travis-ci, coveralls, requires.io (or other equivalent).

### PR DESCRIPTION
**Pull request by IAmAMissingColon**
Added travis-ci, coveralls, requires.io badges 

Can Closes #4

### CODE REVIEW

**Comment by IAmAMissingColon** [comment]
I've a doubt that it's showing `The requested URL /github/openwisp/openwisp-firmware-upgrader/requirements/ was not found on this server.` when clicked on the requirements. Am I doing something wrong ?
but I'm able to see the requirements whenever I replace the `openwisp` with my user id registered to `requires.io`

**Comment by IAmAMissingColon** [comment]
Same thing is happening for both travis and coveralls

**Comment by atb00ker** [comment]
@IAmAMissingColon that's because it needs to be activated before use, I've activated:
- https://coveralls.io/github/openwisp/openwisp-firmware-upgrader
- https://requires.io/github/openwisp/openwisp-firmware-upgrader/requirements/

and pinged @nemesisdesign for activating:

- https://travis-ci.org/openwisp/openwisp-firmware-upgrader

**Comment by IAmAMissingColon** [comment]
Thank You :smile:

**Comment by nemesisdesign** [comment]
I've activated travis too right now.

**Pull request merged**
