### PR TITLE
[permissions] Make FirmwareImage not editable in admin #44

### LINKED ISSUE #44: [fw-upgrader] Make Image firmware file readonly in admin
Prevent users from modifying the firmware image file once it has been uploaded. They will have to create a new one if needed.

### PR DESCRIPTION
**Pull request by PabloCastellano**
Fixes #44

### CODE REVIEW

**Comment by PabloCastellano** [comment]
@nemesisdesign I have tried that and also some variants but can't get it working. It prevents from editing an existing image however it does not display the inputs when adding a new image

image

Apparently it is a known issue in Django when using Inlines: https://stackoverflow.com/questions/6727372/get-readonly-fields-in-a-tabularinline-class-in-django There are different workaround but none of them convinced me. Let me know your opinion.

**Comment by PabloCastellano** [comment]
@nemesisdesign Good news! `has_change_permission` works fine!

Do you want me to remove the changes regarding the admin permissions and just leave this workaround?

**Comment by PabloCastellano** [comment]
I have removed the permissions part. I have also tried to create a test for this, but it was taking me too much time. Do you think we need it?

This is the POST body of the request that is sent when you modify a FirmwareImage.

```
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="csrfmiddlewaretoken"

8FReMsZEO5VcLTajD6Qn9C9K16CYRrllcQiew7mnFXh9VKF02DSXoPIeFRtXWXuE
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="category"

5168b9ae-316d-46b9-8cc3-aa9ad5393e76
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="version"

1
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="changelog"


-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-TOTAL_FORMS"

1
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-INITIAL_FORMS"

1
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-MIN_NUM_FORMS"

0
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-MAX_NUM_FORMS"

1000
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-0-file"; filename=""
Content-Type: application/octet-stream


-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-0-type"

ar71xx-generic-xd3200-squashfs-sysupgrade.bin
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-0-id"

ca007c5c-40c4-4031-acbe-d7b8763cc690
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-0-build"

239ce125-18d2-4548-b9ee-419993eab3a8
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-__prefix__-file"; filename=""
Content-Type: application/octet-stream


-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-__prefix__-type"


-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-__prefix__-id"


-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="firmwareimage_set-__prefix__-build"

239ce125-18d2-4548-b9ee-419993eab3a8
-----------------------------99830827748131133427605661
Content-Disposition: form-data; name="_save"

Save
-----------------------------99830827748131133427605661--
```

**Comment by nemesisdesign** [comment]
Merged manually, added test in https://github.com/openwisp/openwisp-firmware-upgrader/commit/7cac296f31f57976e47aa2456aaf6a293865a999

**Pull request closed without merging**
