### PR TITLE
[ci] Added GitHub workflow for CI #116

### LINKED ISSUE #116: [ci] Move CI to Github actions
Move CI to Github actions as we did with other modules.

### PR DESCRIPTION
**Pull request by devkapilbansal**
Closes #116

### CODE REVIEW

**Comment by devkapilbansal** [comment]
Accidentally created the PR from master branch :zipper_mouth_face:

**Comment by devkapilbansal** [comment]
Tested on my fork and it looks fine https://github.com/devkapilbansal/openwisp-firmware-upgrader/actions

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
@devkapilbansal, can you try to create a branch (from master) called dev, and change the target of the PR to dev? Then you can merge and create a PR from dev to master so we can test it.
Try this so we can also test your permissions. Since you're part of the contributors group of the org, you have write permissions to this repo and you should be able to do this.

Let me know.

**Comment by devkapilbansal** [comment]
@nemesisdesign opened #121 for this

**Pull request merged**
