### PR TITLE
[qa] Add admin checks for details field #61

### LINKED ISSUE #61: [qa] Write admin tests which check the presence of details field in admin UI
The sample app models have a details field which is shown in the admin:

https://github.com/openwisp/openwisp-firmware-upgrader/blob/1136746050f98851d0dc0fb75ec37cb1b02bd10b/tests/openwisp2/sample_firmware_upgrader/models.py#L12-L16

But we don't have automated tests for this.

If this feature breaks, we won't know from tests.

Write additional tests in `tests/openwisp2/sample_firmware_upgrader/tests.py` (TestAdmin) to check this.

One test for each admin class being used.

### PR DESCRIPTION
**Pull request by Purhan**
Closes #61

### CODE REVIEW

**Review by Purhan — COMMENTED** [review]
How can I test `BatchUpgradeOperation` and `UpgradeOperation`? No endpoints show details in the admin interface for these 2 models. Please help.

**Comment by Purhan** [comment]
> How can I test `BatchUpgradeOperation` and `UpgradeOperation`? No endpoints show details in the admin interface for these 2 models. Please help.

The lines below are the reason why. I could overwrite this in the `sample_app/admin.py` to include the details field. Is that a good option?
https://github.com/openwisp/openwisp-firmware-upgrader/blob/d5d82f6442875737f9da6834d9bc558c7af0f7c3/openwisp_firmware_upgrader/admin.py#L194-L203

**Comment by pandafy** [comment]
I think we can also can monkey patch the respective admin class as show in the [documentation](https://github.com/openwisp/openwisp-firmware-upgrader#1-monkey-patching). I believe that should be sufficient for testing. What do you think?

**Comment by Purhan** [comment]
> I think we can also can monkey patch the respective admin class as show in the [documentation](https://github.com/openwisp/openwisp-firmware-upgrader#1-monkey-patching). I believe that should be sufficient for testing. What do you think?

Yes, that's exactly what I mean by overwriting in `sample_app/admin.py`, had to use the correct terminology :smile:

**Comment by Purhan** [comment]
@pandafy Thanks for helping out! I'm marking this as ready for review now. Please take a look/

**Review by nemesisdesign — APPROVED** [review]
Great work @Purhan! Thanks @pandafy for reviewing. :+1:

**Pull request merged**
